import fs from 'node:fs';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {batchStaticCity} from '../../agents/demo_rev02/static-batches.js';
import * as THREE from 'three';
const b=fs.readFileSync('geometry/completion/output/buildings_supplement.glb');
const gltf=await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');
const ids=new Set();let before=0;gltf.scene.traverse(o=>{if(o.userData.building_id)ids.add(o.userData.building_id);if(o.isMesh)before+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;});
const batches=await batchStaticCity(gltf.scene);let after=0;const root=new THREE.Group();root.add(gltf.scene,batches.object);root.traverseVisible(o=>{if(o.isMesh)after+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;});
if(ids.size!==306||before!==after)throw new Error(JSON.stringify({count:ids.size,before,after}));
const result={ids:ids.size,triangles:before,visible_triangles_after_batch:after,draw_batches:batches.object.children.length,passed:true};fs.writeFileSync('geometry/completion/reports/viewer_check.json',JSON.stringify(result,null,2));console.log(result);
